import type { MonthlyData } from "@/data/clientData";

export interface MasterlistAggregates2024 {
  monthlyData: MonthlyData[];
  totals: {
    totalRevenue: number;
    totalInvoices: number;
    totalClients: number;
    avgInvoiceValue: number;
    premiumTotal: number;
    normalTotal: number;
    oneTimeTotal: number;
  };
}

// ========== EXACT 2024 MONTHLY DATA (from user-provided spreadsheets) ==========
const MONTHLY_DATA_2024: MonthlyData[] = [
  {
    month: "January",
    monthNum: 1,
    revenue: 161513,
    invoices: 75,
    clients: 45,
    premiumRevenue: 70457,
    normalRevenue: 74964,
    oneTimeRevenue: 16092,
    premiumInvoices: 37,
    normalInvoices: 27,
    oneTimeInvoices: 11,
    premiumClients: 15,
    normalClients: 18,
    oneTimeClients: 11,
    avgInvoiceValue: 161513 / 75,
    topClients: [
      { name: "Dunecrest School", revenue: 19194, invoices: 2, category: "premium" as const },
      { name: "Navitas / Murdoch", revenue: 10803, invoices: 3, category: "premium" as const },
      { name: "Gulftainer Company", revenue: 10000, invoices: 1, category: "premium" as const },
      { name: "Stellar Advertising", revenue: 9650, invoices: 8, category: "premium" as const },
      { name: "Trane BVBA", revenue: 6380, invoices: 4, category: "premium" as const },
    ],
  },
  {
    month: "February",
    monthNum: 2,
    revenue: 267652,
    invoices: 61,
    clients: 42,
    premiumRevenue: 196117,
    normalRevenue: 45770,
    oneTimeRevenue: 25765,
    premiumInvoices: 34,
    normalInvoices: 19,
    oneTimeInvoices: 8,
    premiumClients: 14,
    normalClients: 12,
    oneTimeClients: 8,
    avgInvoiceValue: 267652 / 61,
    topClients: [
      { name: "IDP Education", revenue: 165011, invoices: 6, category: "premium" as const },
      { name: "Stellar Advertising", revenue: 16016, invoices: 5, category: "premium" as const },
      { name: "Continental Middle East", revenue: 3835, invoices: 2, category: "premium" as const },
      { name: "Trane BVBA", revenue: 3000, invoices: 2, category: "premium" as const },
      { name: "Aurantius Real Estate", revenue: 2410, invoices: 2, category: "premium" as const },
    ],
  },
  {
    month: "March",
    monthNum: 3,
    revenue: 124056,
    invoices: 60,
    clients: 38,
    premiumRevenue: 79836,
    normalRevenue: 27699,
    oneTimeRevenue: 16521,
    premiumInvoices: 42,
    normalInvoices: 10,
    oneTimeInvoices: 8,
    premiumClients: 16,
    normalClients: 8,
    oneTimeClients: 8,
    avgInvoiceValue: 124056 / 60,
    topClients: [
      { name: "GrokGlobal Services", revenue: 22178, invoices: 3, category: "premium" as const },
      { name: "Stellar Advertising", revenue: 18431, invoices: 6, category: "premium" as const },
      { name: "Navitas / Murdoch", revenue: 12395, invoices: 4, category: "premium" as const },
      { name: "Lloyds Energy DMCC", revenue: 9475, invoices: 2, category: "premium" as const },
      { name: "Dubai Academic Health", revenue: 6920, invoices: 2, category: "premium" as const },
    ],
  },
  {
    month: "April",
    monthNum: 4,
    revenue: 94044,
    invoices: 43,
    clients: 30,
    premiumRevenue: 23247,
    normalRevenue: 66232,
    oneTimeRevenue: 4565,
    premiumInvoices: 26,
    normalInvoices: 12,
    oneTimeInvoices: 5,
    premiumClients: 12,
    normalClients: 10,
    oneTimeClients: 5,
    avgInvoiceValue: 94044 / 43,
    topClients: [
      { name: "Stellar Advertising", revenue: 9871, invoices: 4, category: "premium" as const },
      { name: "Navitas / Murdoch", revenue: 4669, invoices: 2, category: "premium" as const },
      { name: "IDP Education", revenue: 4197, invoices: 2, category: "premium" as const },
      { name: "Byyu Gift Trading", revenue: 4225, invoices: 2, category: "premium" as const },
      { name: "Trane BVBA", revenue: 1250, invoices: 1, category: "premium" as const },
    ],
  },
  {
    month: "May",
    monthNum: 5,
    revenue: 132558,
    invoices: 91,
    clients: 50,
    premiumRevenue: 97616,
    normalRevenue: 29931,
    oneTimeRevenue: 5010,
    premiumInvoices: 68,
    normalInvoices: 18,
    oneTimeInvoices: 5,
    premiumClients: 20,
    normalClients: 14,
    oneTimeClients: 5,
    avgInvoiceValue: 132558 / 91,
    topClients: [
      { name: "Stellar Advertising", revenue: 20166, invoices: 8, category: "premium" as const },
      { name: "Navitas / Murdoch", revenue: 18700, invoices: 5, category: "premium" as const },
      { name: "IDP Education", revenue: 16716, invoices: 6, category: "premium" as const },
      { name: "Dubai Academic Health", revenue: 12375, invoices: 3, category: "premium" as const },
      { name: "Tappy Toes Nursery", revenue: 7425, invoices: 2, category: "premium" as const },
    ],
  },
  {
    month: "June",
    monthNum: 6,
    revenue: 278942,
    invoices: 65,
    clients: 42,
    premiumRevenue: 170832,
    normalRevenue: 68096,
    oneTimeRevenue: 40012,
    premiumInvoices: 49,
    normalInvoices: 12,
    oneTimeInvoices: 4,
    premiumClients: 18,
    normalClients: 10,
    oneTimeClients: 4,
    avgInvoiceValue: 278942 / 65,
    topClients: [
      { name: "Stellar Advertising", revenue: 76628, invoices: 12, category: "premium" as const },
      { name: "Navitas / Murdoch", revenue: 35008, invoices: 6, category: "premium" as const },
      { name: "Dubai Academic Health", revenue: 24338, invoices: 4, category: "premium" as const },
      { name: "Dunecrest School", revenue: 14110, invoices: 2, category: "premium" as const },
      { name: "M E A D Medical", revenue: 10070, invoices: 3, category: "premium" as const },
    ],
  },
  {
    month: "July",
    monthNum: 7,
    revenue: 115258,
    invoices: 65,
    clients: 40,
    premiumRevenue: 66844,
    normalRevenue: 37594,
    oneTimeRevenue: 10819,
    premiumInvoices: 44,
    normalInvoices: 12,
    oneTimeInvoices: 9,
    premiumClients: 16,
    normalClients: 10,
    oneTimeClients: 9,
    avgInvoiceValue: 115258 / 65,
    topClients: [
      { name: "Stellar Advertising", revenue: 17208, invoices: 6, category: "premium" as const },
      { name: "IDP Education", revenue: 6260, invoices: 3, category: "premium" as const },
      { name: "Continental Middle East", revenue: 6209, invoices: 2, category: "premium" as const },
      { name: "Byyu Gift Trading", revenue: 5935, invoices: 2, category: "premium" as const },
      { name: "Trane BVBA", revenue: 5129, invoices: 3, category: "premium" as const },
    ],
  },
  {
    month: "August",
    monthNum: 8,
    revenue: 256551,
    invoices: 74,
    clients: 48,
    premiumRevenue: 195301,
    normalRevenue: 45381,
    oneTimeRevenue: 15868,
    premiumInvoices: 50,
    normalInvoices: 15,
    oneTimeInvoices: 9,
    premiumClients: 18,
    normalClients: 12,
    oneTimeClients: 9,
    avgInvoiceValue: 256551 / 74,
    topClients: [
      { name: "Stellar Advertising", revenue: 80215, invoices: 10, category: "premium" as const },
      { name: "Continental Middle East", revenue: 27440, invoices: 4, category: "premium" as const },
      { name: "Navitas / Murdoch", revenue: 23476, invoices: 5, category: "premium" as const },
      { name: "IDP Education", revenue: 20926, invoices: 4, category: "premium" as const },
      { name: "GrokGlobal Services", revenue: 15915, invoices: 3, category: "premium" as const },
    ],
  },
  {
    month: "September",
    monthNum: 9,
    revenue: 305716,
    invoices: 81,
    clients: 52,
    premiumRevenue: 244362,
    normalRevenue: 39624,
    oneTimeRevenue: 21730,
    premiumInvoices: 53,
    normalInvoices: 17,
    oneTimeInvoices: 11,
    premiumClients: 20,
    normalClients: 14,
    oneTimeClients: 11,
    avgInvoiceValue: 305716 / 81,
    topClients: [
      { name: "IDP Education", revenue: 103030, invoices: 8, category: "premium" as const },
      { name: "Navitas / Murdoch", revenue: 63751, invoices: 6, category: "premium" as const },
      { name: "Stellar Advertising", revenue: 21644, invoices: 5, category: "premium" as const },
      { name: "Continental Middle East", revenue: 18375, invoices: 3, category: "premium" as const },
      { name: "GrokGlobal Services", revenue: 11795, invoices: 2, category: "premium" as const },
    ],
  },
  {
    month: "October",
    monthNum: 10,
    revenue: 144394,
    invoices: 81,
    clients: 50,
    premiumRevenue: 67015,
    normalRevenue: 59948,
    oneTimeRevenue: 17431,
    premiumInvoices: 50,
    normalInvoices: 17,
    oneTimeInvoices: 14,
    premiumClients: 18,
    normalClients: 14,
    oneTimeClients: 14,
    avgInvoiceValue: 144394 / 81,
    topClients: [
      { name: "GrokGlobal Services", revenue: 12557, invoices: 3, category: "premium" as const },
      { name: "IDP Education", revenue: 11308, invoices: 4, category: "premium" as const },
      { name: "Continental Middle East", revenue: 11172, invoices: 2, category: "premium" as const },
      { name: "Stellar Advertising", revenue: 9762, invoices: 4, category: "premium" as const },
      { name: "Navitas / Murdoch", revenue: 6427, invoices: 3, category: "premium" as const },
    ],
  },
  {
    month: "November",
    monthNum: 11,
    revenue: 188944,
    invoices: 71,
    clients: 46,
    premiumRevenue: 120280,
    normalRevenue: 58980,
    oneTimeRevenue: 9683,
    premiumInvoices: 43,
    normalInvoices: 19,
    oneTimeInvoices: 9,
    premiumClients: 16,
    normalClients: 14,
    oneTimeClients: 9,
    avgInvoiceValue: 188944 / 71,
    topClients: [
      { name: "Navitas / Murdoch", revenue: 41883, invoices: 6, category: "premium" as const },
      { name: "Dubai Academic Health", revenue: 22720, invoices: 3, category: "premium" as const },
      { name: "IDP Education", revenue: 15176, invoices: 4, category: "premium" as const },
      { name: "Gulftainer Company", revenue: 14292, invoices: 2, category: "premium" as const },
      { name: "Trane BVBA", revenue: 7770, invoices: 3, category: "premium" as const },
    ],
  },
  {
    month: "December",
    monthNum: 12,
    revenue: 143383,
    invoices: 52,
    clients: 38,
    premiumRevenue: 69214,
    normalRevenue: 59106,
    oneTimeRevenue: 15062,
    premiumInvoices: 29,
    normalInvoices: 15,
    oneTimeInvoices: 8,
    premiumClients: 12,
    normalClients: 12,
    oneTimeClients: 8,
    avgInvoiceValue: 143383 / 52,
    topClients: [
      { name: "Gulftainer Company", revenue: 13400, invoices: 2, category: "premium" as const },
      { name: "IDP Education", revenue: 12032, invoices: 3, category: "premium" as const },
      { name: "Navitas / Murdoch", revenue: 9772, invoices: 4, category: "premium" as const },
      { name: "Tappy Toes Nursery", revenue: 9405, invoices: 2, category: "premium" as const },
      { name: "ANB Automobiles", revenue: 8600, invoices: 2, category: "premium" as const },
    ],
  },
];

// Calculate totals from monthly data
const TOTAL_REVENUE_2024 = MONTHLY_DATA_2024.reduce((s, m) => s + m.revenue, 0);
const TOTAL_INVOICES_2024 = MONTHLY_DATA_2024.reduce((s, m) => s + m.invoices, 0);
const PREMIUM_TOTAL = MONTHLY_DATA_2024.reduce((s, m) => s + m.premiumRevenue, 0);
const NORMAL_TOTAL = MONTHLY_DATA_2024.reduce((s, m) => s + m.normalRevenue, 0);
const ONE_TIME_TOTAL = MONTHLY_DATA_2024.reduce((s, m) => s + m.oneTimeRevenue, 0);

// 25 premium + 67 normal + 101 one-time = 193 clients
const TOTAL_CLIENTS_2024 = 193;

export async function loadMasterlistAggregates2024(): Promise<MasterlistAggregates2024> {
  return {
    monthlyData: MONTHLY_DATA_2024,
    totals: {
      totalRevenue: TOTAL_REVENUE_2024,
      totalInvoices: TOTAL_INVOICES_2024,
      totalClients: TOTAL_CLIENTS_2024,
      avgInvoiceValue: TOTAL_REVENUE_2024 / TOTAL_INVOICES_2024,
      premiumTotal: PREMIUM_TOTAL,
      normalTotal: NORMAL_TOTAL,
      oneTimeTotal: ONE_TIME_TOTAL,
    },
  };
}
